# Generated by gallery/generate.py; do not edit.
function little_big_redstone_gallery:clear
# microchip-white: white microchip neutral shell
setblock 176 100 176 little_big_redstone:white_microchip
# microchip-orange: orange microchip neutral shell
setblock 179 100 176 little_big_redstone:orange_microchip
# microchip-magenta: magenta microchip neutral shell
setblock 182 100 176 little_big_redstone:magenta_microchip
# microchip-light_blue: light_blue microchip neutral shell
setblock 185 100 176 little_big_redstone:light_blue_microchip
# microchip-yellow: yellow microchip neutral shell
setblock 176 100 179 little_big_redstone:yellow_microchip
# microchip-lime: lime microchip neutral shell
setblock 179 100 179 little_big_redstone:lime_microchip
# microchip-pink: pink microchip neutral shell
setblock 182 100 179 little_big_redstone:pink_microchip
# microchip-gray: gray microchip neutral shell
setblock 185 100 179 little_big_redstone:gray_microchip
# microchip-light_gray: light_gray microchip neutral shell
setblock 176 100 182 little_big_redstone:light_gray_microchip
# microchip-cyan: cyan microchip neutral shell
setblock 179 100 182 little_big_redstone:cyan_microchip
# microchip-purple: purple microchip neutral shell
setblock 182 100 182 little_big_redstone:purple_microchip
# microchip-blue: blue microchip neutral shell
setblock 185 100 182 little_big_redstone:blue_microchip
# microchip-brown: brown microchip neutral shell
setblock 176 100 185 little_big_redstone:brown_microchip
# microchip-green: green microchip neutral shell
setblock 179 100 185 little_big_redstone:green_microchip
# microchip-red: red microchip neutral shell
setblock 182 100 185 little_big_redstone:red_microchip
# microchip-black: black microchip neutral shell
setblock 185 100 185 little_big_redstone:black_microchip
# stock-control: stone stock rendering control
setblock 190 100 185 minecraft:stone
function little_big_redstone_gallery:verify
