# Generated by gallery/generate.py; do not edit.
function little_big_redstone_gallery:clear
# stock-control: stone stock rendering control
setblock 176 100 175 minecraft:stone
function little_big_redstone_gallery:verify
