# Generated by gallery/generate.py; do not edit.
execute unless block 176 100 175 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"Little Big Redstone placeholder gallery checked","color":"yellow"}
