# Generated by gallery/generate.py; do not edit.
execute unless block 176 100 176 little_big_redstone:white_microchip run tellraw @a {"text":"gallery mismatch: microchip-white","color":"red"}
execute unless block 179 100 176 little_big_redstone:orange_microchip run tellraw @a {"text":"gallery mismatch: microchip-orange","color":"red"}
execute unless block 182 100 176 little_big_redstone:magenta_microchip run tellraw @a {"text":"gallery mismatch: microchip-magenta","color":"red"}
execute unless block 185 100 176 little_big_redstone:light_blue_microchip run tellraw @a {"text":"gallery mismatch: microchip-light_blue","color":"red"}
execute unless block 176 100 179 little_big_redstone:yellow_microchip run tellraw @a {"text":"gallery mismatch: microchip-yellow","color":"red"}
execute unless block 179 100 179 little_big_redstone:lime_microchip run tellraw @a {"text":"gallery mismatch: microchip-lime","color":"red"}
execute unless block 182 100 179 little_big_redstone:pink_microchip run tellraw @a {"text":"gallery mismatch: microchip-pink","color":"red"}
execute unless block 185 100 179 little_big_redstone:gray_microchip run tellraw @a {"text":"gallery mismatch: microchip-gray","color":"red"}
execute unless block 176 100 182 little_big_redstone:light_gray_microchip run tellraw @a {"text":"gallery mismatch: microchip-light_gray","color":"red"}
execute unless block 179 100 182 little_big_redstone:cyan_microchip run tellraw @a {"text":"gallery mismatch: microchip-cyan","color":"red"}
execute unless block 182 100 182 little_big_redstone:purple_microchip run tellraw @a {"text":"gallery mismatch: microchip-purple","color":"red"}
execute unless block 185 100 182 little_big_redstone:blue_microchip run tellraw @a {"text":"gallery mismatch: microchip-blue","color":"red"}
execute unless block 176 100 185 little_big_redstone:brown_microchip run tellraw @a {"text":"gallery mismatch: microchip-brown","color":"red"}
execute unless block 179 100 185 little_big_redstone:green_microchip run tellraw @a {"text":"gallery mismatch: microchip-green","color":"red"}
execute unless block 182 100 185 little_big_redstone:red_microchip run tellraw @a {"text":"gallery mismatch: microchip-red","color":"red"}
execute unless block 185 100 185 little_big_redstone:black_microchip run tellraw @a {"text":"gallery mismatch: microchip-black","color":"red"}
execute unless block 190 100 185 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"Little Big Redstone gallery checked","color":"green"}
